### ISSUE TITLE
GWD composite for SES - all dates vs dates after 2008

### ISSUE THREAD

**Issue by kuchaale** [VACILT/SSW_project#23]
We should check the sensitivity of the SES composite when all dates and only dates after 2008 are included (see below). 
![obrazek](https://user-images.githubusercontent.com/6815953/123293410-3fb7bb80-d514-11eb-843b-ee3b80cf4a1a.png)

The amplitude may be underestimated before 2008, however, composite anomalies may not be influenced.

**Comment by gast-ben** [comment]
The analysis only for dates after 2008 shows minor differences in:

- gravity wave drag: lower values of gravity wave drag around 20 to 30 days before the SSW onset
- planetary wave activity: maximum of PW activity around the SSW onset reaches higher altitudes and is more narrow time
- zonal wind: stronger wind reverse shortly after the onset
- meridional wind: maximum of northerly wind around lag -10 less pronounced; maximum of southerly wind time-shifted to some days before the onset instead of around the onset
